#
# General Configuration
# Note: Notifications are managed through secrets.
#
owner: zyradyl-moe
repo: status-page
user-agent: yuno-senpai

#
# Status Page Configuration
#
status-website:
  cname: status.zyradyl.moe
  logoUrl: https://miyuki.zyradyl.moe/img/zyradyl-moe.png
  name: System Status
  introTitle: "Zyradyl.moe System Status"
  introMessage: This is a status page for tracking the various services available through zyradyl.moe
  navbar:
    - title: Status
      href: /
    - title: Repo
      href: https://github.com/zyradyl-moe/status-page/tree/master
  theme: night

#
# Git Configuration
#
commitMessages:
  commitAuthorName: "Yuno Senpai"
  commitAuthorEmail: "maple@zyradyl.moe"

#
# Endpoints Configuration
#
sites:
  - name: Auth Portal
    icon: https://www.authelia.com/favicon.ico
    maxResponseTime: 5000 
    url: https://auth.zyradyl.moe
  - name: Maple - Admin Portal
    icon: https://heimdall.site/favicon-32x32.png
    maxResponseTime: 5000
    url: https://admin.zyradyl.moe
  - name: Maple - Cloud Services
    icon: https://www.seafile.com/media/img/favicon.png
    maxResponseTime: 5000
    url: https://files.zyradyl.moe
  - name: Maple - Media Browser
    icon: https://3149836655-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/spaces%2F-M8KDxOujDoPpJyJJ5_i%2Favatar-1590579241040.png?generation=1590579241552005&alt=media
    maxResponseTime: 5000
    url: https://browse.zyradyl.moe
  - name: Maple - Request Service
    icon: https://request.zyradyl.moe/favicon-32x32.png
    maxResponseTime: 5000
    url: https://request.zyradyl.moe
  - name: Maple - User Portal
    icon: https://zyradyl.moe/images/icons/favicon-32x32.png
    maxResponseTime: 5000
    url: https://maple.zyradyl.moe
  - name: Maple - Watch Service
    icon: https://jellyfin.org/images/favicon.ico
    maxResponseTime: 5000
    url: https://watch.zyradyl.moe
  - name: Storj Node Service
    icon: https://assets-global.website-files.com/602eda09fc78afc76e9706b6/607db1d3d1a195db98b50743_storj-favicon-32.png
    check: "tcp-ping"
    maxResponseTime: 5000
    port: 28967
    url: maple.zyradyl.moe

assignees: # these users will be assigned to the autogenerated issues
  - zyradyl

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  summary: "5 * * * *"
