#
# General Configuration
#
owner: zyradyl-moe
repo: status-page
user-agent: zyradyl

#
# Status Page Configuration
#
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zyradyl.moe
  # baseUrl: /your-repo-name
  logoUrl: https://miyuki.zyradyl.moe/img/zyradyl-moe.png
  name: System Status
  introTitle: "Zyradyl.moe System Status"
  introMessage: This is a status page for tracking the various services available through zyradyl.moe
  navbar:
    - title: Status
      href: /
    - title: Repo
      href: https://github.com/zyradyl-moe/status-page/tree/master
  theme: dark

#
# Git Configuration
#
commitMessages:
  commitAuthorName: "Yuno Senpai"
  commitAuthorEmail: "yuno@zyradyl.moe"

#
# Monitoring Configuration
#
sites:
  - name: Auth Portal
    url: $AUTH_PORTAL
    maxResponseTime: 5000
  - name: Cloud Services
    url: $CLOUD_SERVICE
    maxResponseTime: 5000
  - name: Maple - Admin Portal
    url: $ADMIN_PORTAL
    maxResponseTime: 5000
  - name: Maple - Request Service
    url: $REQUEST_SERVICE
    maxResponseTime: 5000
  - name: Maple - User Portal
    url: $MAPLE_ADDRESS
    maxResponseTime: 5000
  - name: Maple - Watch Service
    url: $WATCH_SERVICE
    maxResponseTime: 5000
  - name: Storj Node Service
    check: "tcp-ping"
    url: $MAPLE_ADDRESS
    maxResponseTime: 5000
    port: 28967

#
# Notification Configuration
# NOTE: Webhook configuration is done through secrets.
#
assignees: # these users will be assigned to the autogenerated issues
  - zyradyl

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  summary: "5 * * * *"
